export const SEARCH = {
  SEARCH: 'SEARCH/SEARCH',
  SEARCH_SUCCESS: 'SEARCH/SEARCH_SUCCESS',
  SEARCH_FAILURE: 'SEARCH/SEARCH_FAILURE',
  SEARCH_PENDING: 'SEARCH/SEARCH_PENDING',
  SEARCH_BY_ONTOLOGY: 'SEARCH/SEARCH_BY_ONTOLOGY',
  SEARCH_BY_ONTOLOGY_SUCCESS: 'SEARCH/SEARCH_BY_ONTOLOGY_SUCCESS',
  SEARCH_BY_ONTOLOGY_FAILURE: 'SEARCH/SEARCH_BY_ONTOLOGY_FAILURE',
  SEARCH_BY_ONTOLOGY_PENDING: 'SEARCH/SEARCH_BY_ONTOLOGY_PENDING'
};

export const DATASET = {
  FETCH_DATASET: 'DATASET/FETCH_DATASET',
  FETCH_DATASET_SUCCESS: 'DATASET/FETCH_DATASET_SUCCESS',
  FETCH_DATASET_FAILURE: 'DATASET/FETCH_DATASET_FAILURE',
  FETCH_DATASET_PENDING: 'DATASET/FETCH_DATASET_PENDING'
};

export const ONTOLOGY = {
  FETCH_ONTOLOGIES: 'ONTOLOGY/FETCH_ONTOLOGIES',
  FETCH_ONTOLOGIES_SUCCESS: 'ONTOLOGY/FETCH_ONTOLOGIES_SUCCESS',
  FETCH_ONTOLOGIES_FAILURE: 'ONTOLOGY/FETCH_ONTOLOGIES_FAILURE',
  FETCH_ONTOLOGIES_PENDING: 'ONTOLOGY/FETCH_ONTOLOGIES_PENDING',

  SEARCH_BY_NODE: 'ONTOLOGY/SEARCH_BY_NODE',
  SEARCH_BY_NODE_SUCCESS: 'ONTOLOGY/SEARCH_BY_NODE_SUCCESS',
  SEARCH_BY_NODE_FAILURE: 'ONTOLOGY/SEARCH_BY_NODE_FAILURE',
  SEARCH_BY_NODE_PENDING: 'ONTOLOGY/SEARCH_BY_NODE_PENDING',

  GET_NODES_BY_DATASET: 'ONTOLOGY/GET_NODES_BY_DATASET',
  GET_NODES_BY_DATASET_SUCCESS: 'ONTOLOGY/GET_NODES_BY_DATASET_SUCCESS',
  GET_NODES_BY_DATASET_FAILURE: 'ONTOLOGY/GET_NODES_BY_DATASET_FAILURE',
  GET_NODES_BY_DATASET_PENDING: 'ONTOLOGY/GET_NODES_BY_DATASET_PENDING'
};
